# Generated by Django 5.0.7 on 2024-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('trainer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='null', max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('experience', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=100)),
                ('trainer_pic', models.FileField(default=' ', upload_to='class_app/trainer_images')),
            ],
        ),
    ]
