# Generated by Django 5.0.7 on 2024-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('fees', models.BooleanField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='class_app/syllabus')),
            ],
        ),
    ]
