# Generated by Django 5.0.7 on 2024-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyresources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='class_app/resourses')),
                ('date', models.DateField()),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
    ]
