# Generated by Django 5.0.7 on 2024-08-07 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_Doubts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('member_id', models.CharField(default='', max_length=45)),
                ('question', models.TextField(max_length=150)),
                ('answer', models.TextField(default='')),
                ('question_date', models.DateField(default=django.utils.timezone.now)),
                ('answer_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
