# Generated by Django 5.0.7 on 2024-08-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0008_query_doubts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
