# Generated by Django 5.0.7 on 2024-08-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0010_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
