# Generated by Django 5.0.7 on 2024-09-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0012_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('notes_pdf', models.FileField(blank=True, null=True, upload_to='notes/')),
            ],
        ),
    ]
