# Generated by Django 5.0.7 on 2024-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0013_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
